### ISSUE TITLE
Install aws cli installs the wrong python dependency

### ISSUE THREAD

**Issue by maxkramer** [CircleCI-Public/aws-cli-orb#16]
I'm using the https://github.com/CircleCI-Public/aws-eks-orb, version and specifically the aws-eks/update-kubeconfig-with-authenticator@0.2.0  task which triggers the aws-cli/install command.

Over the past day or so, it has started failing with the following error: 

```
#!/bin/bash -eo pipefail
CLUSTER_NAME="redacted"
AWS_REGION="eu-central-1"
AWS_PROFILE=""
KUBECONFIG_FILE_PATH=""
ROLE_ARN="redacted"
CLUSTER_CONTEXT_ALIAS=""
DRY_RUN="false"
VERBOSE="true"
if [ -n "${CLUSTER_NAME}" ]; then
  set -- "$@" --name "${CLUSTER_NAME}"
fi
if [ -n "${AWS_REGION}" ]; then
  set -- "$@" --region "${AWS_REGION}"
fi
if [ -n "${AWS_PROFILE}" ]; then
  set -- "$@" --profile "${AWS_PROFILE}"
fi
if [ -n "${KUBECONFIG_FILE_PATH}" ]; then
  set -- "$@" --kubeconfig "${KUBECONFIG_FILE_PATH}"
fi
if [ -n "${ROLE_ARN}" ]; then
  set -- "$@" --role-arn "${ROLE_ARN}"
fi
if [ -n "${CLUSTER_CONTEXT_ALIAS}" ]; then
  set -- "$@" --alias "${CLUSTER_CONTEXT_ALIAS}"
fi
if [ "${DRY_RUN}" == "true" ]; then
  set -- "$@" --dry-run
fi
if [ "${VERBOSE}" == "true" ]; then
  set -- "$@" --verbose
fi
aws eks update-kubeconfig "$@"
Traceback (most recent call last):
  File "/root/.local/bin/aws", line 6, in <module>
    from aws.main import main
  File "/root/.local/lib/python3.7/site-packages/aws/main.py", line 23
    print '%(name)s: %(endpoint)s' % {
                                 ^
SyntaxError: invalid syntax
Exited with code 1
```
This error takes place when the aws library has been installed via pip instead of the awscli library.

Having checked the code that was run in the install aws sdk task, it was clear that this is the issue. The code that was run is:

```
#!/bin/bash -eo pipefail
export PIP=$(which pip pip3 | head -1)
if [[ -n $PIP ]]; then
  if which sudo > /dev/null; then
    sudo $PIP install awscli --upgrade
  else
    # This installs the AWS CLI to ~/.local/bin. Make sure that ~/.local/bin is in your $PATH.
    $PIP install *aws* --upgrade --user
  fi
elif [[ $(which unzip curl | wc -l) -eq 2 ]]; then
  cd
  curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
  unzip awscli-bundle.zip
  if which sudo > /dev/null; then
    sudo ~/awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
  else
    # This installs the AWS CLI to the default location (~/.local/lib/aws) and create a symbolic link (symlink) at ~/bin/aws. Make sure that ~/bin is in your $PATH.
    awscli-bundle/install -b ~/bin/aws
  fi
  rm -rf awscli-bundle*
  cd -
else
  echo "Unable to install AWS CLI. Please install pip."
  exit 1
fi
```

In bold, you can see the issue. When `sudo` is available, it installs the awscli library, however when `sudo` isn't available, it installs the aws library.

I've tried tracing it back into this repository and also the aws-eks-orb repo, and I can't find any reference to this code. It looks like the aws-eks-orb is using aws-cli: [circleci/aws-cli@0.1.9](https://github.com/CircleCI-Public/aws-eks-orb/blob/master/src/%40orb.yml)

**Comment by lokst** [comment]
@maxkramer Thanks for reporting this to us, we'll investigate it and get back to you as soon as possible.

**Comment by lokst** [comment]
@maxkramer Could you link us to a build where this happens?

**Comment by maxkramer** [comment]
@lokst my pleasure. Happy to send you a link, however I would only like to share it privately. Please could you follow me on Twitter (so that I can DM it to you) or alternatively provide me with your email address?

**Comment by lokst** [comment]
Thanks @maxkramer, would you mind opening a support ticket at https://support.circleci.com/hc/en-us/requests/new to share the link?

**Comment by maxkramer** [comment]
@lokst the support ticket id is 56057

**Comment by maxkramer** [comment]
@lokst I can see that the version 0.1.9 is being used by the eks orb, and the source code for 0.1.9 shows the bug in the install command: https://circleci.com/orbs/registry/orb/circleci/aws-cli?version=0.1.9.

Fix would be upgrading the version used in the eks orb to the latest version.
