### ISSUE TITLE
cannot install AWS CLI: RequirementParseError: Expected ',' or end-of-list

### ISSUE THREAD

**Issue by mhmd-rezaei** [CircleCI-Public/aws-cli-orb#72]
Recently I realized the new pipelines cannot install AWS-CLI anymore:

```
Collecting awscli
  Downloading https://files.pythonhosted.org/packages/10/00/fc506c3bbeaec4ab4da4c33194582b85e0e0d6452a6f14aba6fff66c6b33/awscli-1.19.48.tar.gz (1.4MB)
    100% |████████████████████████████████| 1.4MB 761kB/s eta 0:00:01
Exception:
Traceback (most recent call last):
  File "/opt/circleci/.pyenv/versions/2.7.12/lib/python2.7/site-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/opt/circleci/.pyenv/versions/2.7.12/lib/python2.7/site-packages/pip/commands/install.py", line 299, in run
    requirement_set.prepare_files(finder)
  File "/opt/circleci/.pyenv/versions/2.7.12/lib/python2.7/site-packages/pip/req/req_set.py", line 360, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/opt/circleci/.pyenv/versions/2.7.12/lib/python2.7/site-packages/pip/req/req_set.py", line 647, in _prepare_file
    set(req_to_install.extras) - set(dist.extras)
  File "/opt/circleci/.pyenv/versions/2.7.12/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2810, in extras
    return [dep for dep in self._dep_map if dep]
  File "/opt/circleci/.pyenv/versions/2.7.12/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2624, in _dep_map
    dm.setdefault(extra,[]).extend(parse_requirements(reqs))
  File "/opt/circleci/.pyenv/versions/2.7.12/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2980, in parse_requirements
    "version spec")
  File "/opt/circleci/.pyenv/versions/2.7.12/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2956, in scan_list
    raise RequirementParseError(msg, line, "at", line[p:])
RequirementParseError: Expected ',' or end-of-list in rsa>=3.1.2,<=4.5.0; python_version=="2.7" at ; python_version=="2.7"
You are using pip version 8.1.1, however version 21.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

Exited with code exit status 2
```

If you check the file name that it tries to install is `awscli-1.19.48.tar.gz` and it cannot be installed but when I check the old pipelines the candidate file to be installed is `awscli-1.19.44-py2.py3-none-any.whl`

Any Idea?

**Comment by mhmd-rezaei** [comment]
Just needed to update the version
